app:
  title: C++ Lab (Template Project)
  description: 這是用來測試C++ Lab的模板專案
problems:
  p1:
    name: Calculator
    points: 100
    timeout: 1
    required:
    - calculate
  p2:
    name: Recursion Sum
    points: 100
    timeout: 1
    forbidden:
    - for
    - while
    - do
    required:
    - sum
  p3:
    name: Climbing Stairs
    points: 100
    timeout: 1
    forbidden:
    - for
    - while
    - do
    required:
    - climb
  p4:
    name: McCarthy 91
    points: 100
    timeout: 1
    forbidden:
    - for
    - while
    - do
    required:
    - f91
defaults:
  timeout: 1
